threshold: 0.9            # threshold for the confidence score
                          # explanations will be generated for detections with confidence score > threshold

no_object_id: 19          # id for the no-object class
                          # used to filter no-object detections

include_labels: all     # labels to include in the evaluation
                          # use 'all' to include all labels listed in `id2label` key
                          # use a list of category names to include specific labels e.g.
# include_labels: 
#   - person
                   
id2label:                 # list of labels with their ids and names
  0: road
  1: sidewalk
  2: building
  3: wall
  4: fence
  5: pole
  6: traffic light
  7: traffic sign
  8: vegetation
  9: terrain
  10: sky
  11: person
  12: rider
  13: car
  14: truck
  15: bus
  16: train
  17: motorcycle
  18: bicycle
